const A=require('./index.js');
const B={date:'2006-06-25',time:'09:09',latitude:18.5204,longitude:73.8567,timezone:'Asia/Kolkata'};
const r=A.calculateBirthChart(B);const pl=Array.isArray(r.planets)?r.planets:Object.values(r.planets);
const L=r.lagna,m=pl.find(p=>p.name==='Moon');
console.log('LAGNA',L.signName,L.degreeInSign.toFixed(2));
pl.forEach(p=>console.log(p.name.padEnd(8),p.signName.padEnd(12),p.degreeInSign.toFixed(2).padStart(6),'H'+(((p.signNumber-L.signNumber+12)%12)+1),p.nakshatra,p.retrograde?'R':'',p.dignity||''));
let nak=m.nakshatra;if(nak==='Mula')nak='Moola';
const d=A.calculateVimshottariDasha(new Date('2006-06-25T09:09:00+05:30'),nak,(m.longitude%13.3333333),3);
const T=new Date('2026-08-16');
const md=d.mahaDashas.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
const ad=md.subPeriods.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
console.log('\nMD',md.planet,(''+md.startDate).slice(0,10),(''+md.endDate).slice(0,10),'| AD',ad.planet,(''+ad.startDate).slice(0,10),(''+ad.endDate).slice(0,10));
console.log('ADs:');md.subPeriods.forEach(p=>console.log('  ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('MDs:');d.mahaDashas.slice(0,6).forEach(p=>console.log('  ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('\nMANGLIK:',JSON.stringify(A.analyzeManglik(pl,r.houses,L.signNumber)));
console.log('\nSWEEP:');[-15,-10,-5,0,5,10,15].forEach(o=>{const t=new Date(Date.UTC(2006,5,25,9,9)+o*60000);
 const rr=A.calculateBirthChart({...B,time:String(t.getUTCHours()).padStart(2,'0')+':'+String(t.getUTCMinutes()).padStart(2,'0')});
 console.log('  ',(o+'min').padStart(6),rr.lagna.signName,rr.lagna.degreeInSign.toFixed(2));});
console.log('\nTRANSITS:');['2026-08-16','2027-01-01','2027-09-01','2028-06-01','2029-06-01','2030-06-01','2031-06-01','2032-06-01'].forEach(ds=>{
 const t=A.calculateBirthChart({date:ds,time:'12:00',latitude:18.52,longitude:73.86,timezone:'Asia/Kolkata'});
 const tp=Array.isArray(t.planets)?t.planets:Object.values(t.planets);
 console.log('  ',ds,['Jupiter','Saturn','Rahu'].map(n=>{const p=tp.find(x=>x.name===n);return n.slice(0,2)+':'+p.signName+' '+p.degreeInSign.toFixed(0)+(p.retrograde?'R':'')}).join(' '));});
