const A=require('./index.js');
const B={date:'1997-09-03',time:'10:30',latitude:26.6431,longitude:74.0357,timezone:'Asia/Kolkata'};
const r=A.calculateBirthChart(B);const pl=Array.isArray(r.planets)?r.planets:Object.values(r.planets);
const L=r.lagna,m=pl.find(p=>p.name==='Moon');
console.log('LAGNA',L.signName,L.degreeInSign.toFixed(2),'| MOON',m.signName);
pl.forEach(p=>console.log(p.name.padEnd(8),p.signName.padEnd(12),p.degreeInSign.toFixed(2).padStart(6),'H'+(((p.signNumber-L.signNumber+12)%12)+1),p.nakshatra,p.retrograde?'R':'',p.dignity||''));
let nak=m.nakshatra;if(nak==='Mula')nak='Moola';
const d=A.calculateVimshottariDasha(new Date('1997-09-03T10:30:00+05:30'),nak,(m.longitude%13.3333333),3);
const T=new Date('2026-08-16');
const md=d.mahaDashas.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
const ad=md.subPeriods.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
const pd=(ad.subPeriods||[]).find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
console.log('\nMD',md.planet,(''+md.startDate).slice(0,10),(''+md.endDate).slice(0,10),'| AD',ad.planet,(''+ad.startDate).slice(0,10),(''+ad.endDate).slice(0,10),'| PD',pd&&pd.planet);
console.log('ADs:');md.subPeriods.forEach(p=>console.log('  ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('PDs cur AD:');(ad.subPeriods||[]).forEach(p=>console.log('    ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('MDs:');d.mahaDashas.slice(0,5).forEach(p=>console.log('  ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('\nSWEEP:');[-15,-10,-5,0,5,10,15].forEach(o=>{const t=new Date(Date.UTC(1997,8,3,10,30)+o*60000);
 const rr=A.calculateBirthChart({...B,time:String(t.getUTCHours()).padStart(2,'0')+':'+String(t.getUTCMinutes()).padStart(2,'0')});
 console.log('  ',(o+'min').padStart(6),rr.lagna.signName,rr.lagna.degreeInSign.toFixed(2));});
console.log('\nTRANSITS:');['2026-08-16','2026-12-01','2027-04-01','2027-09-01','2028-04-01','2029-01-01','2030-01-01'].forEach(ds=>{
 const t=A.calculateBirthChart({date:ds,time:'12:00',latitude:26.64,longitude:74.04,timezone:'Asia/Kolkata'});
 const tp=Array.isArray(t.planets)?t.planets:Object.values(t.planets);
 console.log('  ',ds,['Jupiter','Saturn','Rahu'].map(n=>{const p=tp.find(x=>x.name===n);return n.slice(0,2)+':'+p.signName+' '+p.degreeInSign.toFixed(0)+(p.retrograde?'R':'')}).join(' '));});
