const A=require('./index.js');
const ABBR={Sun:'Su',Moon:'Mo',Mars:'Ma',Mercury:'Me',Jupiter:'Ju',Venus:'Ve',Saturn:'Sa',Rahu:'Ra',Ketu:'Ke'};
// Arghakhanchi (Sandhikharka) 27.9463N 83.1183E; 23 Jun 1993 20:06 NPT => UTC 14:21
const birth={date:'1993-06-23',time:'20:06',latitude:27.9463,longitude:83.1183,timezone:'Asia/Kathmandu'};
const res=A.calculateBirthChart(birth);
const plist=Array.isArray(res.planets)?res.planets:Object.values(res.planets);
const m=plist.find(p=>p.name==='Moon');
console.log('LAGNA',res.lagna.signName,res.lagna.signNumber,res.lagna.nakshatra,'| MOON',m.signName,m.nakshatra);
(res.houses||[]).forEach(h=>console.log('H'+(h.houseNumber||h.number),h.signName||h.sign,(h.planets||[]).map(x=>x.name||x).join(',')));
plist.forEach(p=>console.log('P',ABBR[p.name],p.signName||p.sign,'deg='+(p.degree!=null?p.degree.toFixed(2):(p.longitude||0).toFixed(2)),'nak='+p.nakshatra,'dig='+(p.dignity||''),'retro='+!!p.retrograde));
console.log('MANGLIK',JSON.stringify(A.analyzeManglik(plist,res.houses)));
const L=res.lagna;
const d9=A.calculateDivisionalChart(9,plist,L.signNumber,L.degree!=null?L.degree:(L.longitude%30));
const lag=d9.lagnaSign.number;
console.log('D9 LAGNA',d9.lagnaSign.name);
d9.planets.forEach(p=>console.log('D9',p.planet,p.vargaSignName,'house='+(((p.vargaSignNumber-lag+12)%12)+1)));
const d=A.calculateVimshottariDasha(new Date('1993-06-23T14:21:00Z'),m.nakshatra,(m.longitude%13.3333333),3);
const TODAY=new Date('2026-07-19');
const md=d.mahaDashas.find(p=>new Date(p.startDate)<=TODAY&&new Date(p.endDate)>TODAY);
console.log('MD',md.planet,(''+md.startDate).slice(0,10),'→',(''+md.endDate).slice(0,10));
md.subPeriods.forEach(p=>{if(new Date(p.endDate)>new Date('2025-01-01')&&new Date(p.startDate)<new Date('2032-01-01'))console.log(' AD',p.planet,(''+p.startDate).slice(0,10),'→',(''+p.endDate).slice(0,10));});
const ad=md.subPeriods.find(p=>new Date(p.startDate)<=TODAY&&new Date(p.endDate)>TODAY);
console.log('CUR AD',ad.planet);
(ad.subPeriods||[]).forEach(p=>console.log('   PD',p.planet,(''+p.startDate).slice(0,10),'→',(''+p.endDate).slice(0,10)));
const i=md.subPeriods.indexOf(ad);
[1,2].forEach(k=>{const n=md.subPeriods[i+k];if(n){console.log(' NEXT AD',n.planet,(''+n.startDate).slice(0,10),'→',(''+n.endDate).slice(0,10));(n.subPeriods||[]).forEach(p=>console.log('    PD',p.planet,(''+p.startDate).slice(0,10),'→',(''+p.endDate).slice(0,10)));}});
const mi=d.mahaDashas.indexOf(md);if(d.mahaDashas[mi+1])console.log('NEXT MD',d.mahaDashas[mi+1].planet,(''+d.mahaDashas[mi+1].startDate).slice(0,10));
