const A=require('./index.js');
const B={date:'1996-03-08',time:'06:45',latitude:26.5679,longitude:88.0847,timezone:'Asia/Kathmandu'};
const r=A.calculateBirthChart(B);
const pl=Array.isArray(r.planets)?r.planets:Object.values(r.planets);
const L=r.lagna,m=pl.find(p=>p.name==='Moon');
console.log('LAGNA',L.signName,L.degreeInSign.toFixed(2),'signNum',L.signNumber);
pl.forEach(p=>console.log(p.name,p.signName,(p.degreeInSign!=null?p.degreeInSign.toFixed(2):''),p.nakshatra,'pada'+(p.pada||''),p.retrograde?'R':'',p.dignity||''));
let nak=m.nakshatra; if(nak==='Mula')nak='Moola';
const d=A.calculateVimshottariDasha(new Date('1996-03-08T06:45:00+05:45'),nak,(m.longitude%13.3333333),3);
const T=new Date('2026-08-16');
const md=d.mahaDashas.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
const ad=md.subPeriods.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
const pd=ad.subPeriods&&ad.subPeriods.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
console.log('\nMD',md.planet,(''+md.startDate).slice(0,10),(''+md.endDate).slice(0,10));
console.log('AD',ad.planet,(''+ad.startDate).slice(0,10),(''+ad.endDate).slice(0,10),'| PD',pd&&pd.planet,pd&&(''+pd.startDate).slice(0,10),pd&&(''+pd.endDate).slice(0,10));
console.log('\n-- ADs in current MD --');
md.subPeriods.forEach(p=>console.log(' ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('\n-- MD timeline --');
d.mahaDashas.forEach(p=>console.log(' ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
const d9=A.calculateDivisionalChart(r,'D9');
console.log('\nD9 lagna',d9.lagna&&(d9.lagna.signName||d9.lagna.sign));
(d9.planets?(Array.isArray(d9.planets)?d9.planets:Object.values(d9.planets)):[]).forEach(p=>console.log(' D9',p.name,p.signName||p.sign));
