const A=require('./index.js');
// Rohtak 28.8955N 76.6066E; 18 Aug 2001 13:27 IST => UTC 07:57
const birth={date:'2001-08-18',time:'13:27',latitude:28.8955,longitude:76.6066,timezone:'Asia/Kolkata'};
const res=A.calculateBirthChart(birth);
const plist=Array.isArray(res.planets)?res.planets:Object.values(res.planets);
const m=plist.find(p=>p.name==='Moon');
console.log('LAGNA',res.lagna.signName,res.lagna.signNumber,res.lagna.nakshatra,'deg',res.lagna.degreeInSign,'| MOON',m.signName,m.nakshatra);
(res.houses||[]).forEach(h=>console.log('H'+(h.houseNumber||h.number),h.signName||h.sign,(h.planets||[]).map(x=>x.name||x).join(',')));
plist.forEach(p=>console.log('P',p.name,p.signName,'deg='+p.degreeInSign,'nak='+p.nakshatra,'dig='+p.dignity,'retro='+p.retrograde,'combust='+p.isCombust));
console.log('MANGLIK',JSON.stringify(A.analyzeManglik(plist,res.houses)));
const L=res.lagna;
const d9=A.calculateDivisionalChart(9,plist,L.signNumber,L.degreeInSign);
const lag=d9.lagnaSign.number;
console.log('D9 LAGNA',d9.lagnaSign.name);
d9.planets.forEach(p=>console.log('D9',p.planet,p.vargaSignName,'house='+(((p.vargaSignNumber-lag+12)%12)+1)));
const d=A.calculateVimshottariDasha(new Date('2001-08-18T07:57:00Z'),m.nakshatra,(m.longitude%13.3333333),3);
const TODAY=new Date('2026-07-19');
const md=d.mahaDashas.find(p=>new Date(p.startDate)<=TODAY&&new Date(p.endDate)>TODAY);
console.log('MD',md.planet,(''+md.startDate).slice(0,10),'→',(''+md.endDate).slice(0,10));
md.subPeriods.forEach(p=>{if(new Date(p.endDate)>new Date('2025-06-01')&&new Date(p.startDate)<new Date('2033-01-01'))console.log(' AD',p.planet,(''+p.startDate).slice(0,10),'→',(''+p.endDate).slice(0,10));});
const ad=md.subPeriods.find(p=>new Date(p.startDate)<=TODAY&&new Date(p.endDate)>TODAY);
console.log('CUR AD',ad.planet);
(ad.subPeriods||[]).forEach(p=>console.log('   PD',p.planet,(''+p.startDate).slice(0,10),'→',(''+p.endDate).slice(0,10)));
const i=md.subPeriods.indexOf(ad);
[1,2].forEach(k=>{const n=md.subPeriods[i+k];if(n){console.log(' NEXT AD',n.planet,(''+n.startDate).slice(0,10),'→',(''+n.endDate).slice(0,10));(n.subPeriods||[]).forEach(p=>console.log('    PD',p.planet,(''+p.startDate).slice(0,10),'→',(''+p.endDate).slice(0,10)));}});
const mi=d.mahaDashas.indexOf(md);if(d.mahaDashas[mi+1])console.log('NEXT MD',d.mahaDashas[mi+1].planet,(''+d.mahaDashas[mi+1].startDate).slice(0,10),'→',(''+d.mahaDashas[mi+1].endDate).slice(0,10));
