const A=require('./index.js');
const B={date:'1995-12-02',time:'15:30',latitude:26.60,longitude:87.90,timezone:'Asia/Kathmandu'};
const r=A.calculateBirthChart(B);
const pl=Array.isArray(r.planets)?r.planets:Object.values(r.planets);
const L=r.lagna,m=pl.find(p=>p.name==='Moon');
console.log('LAGNA',L.signName,L.degreeInSign.toFixed(2));
pl.forEach(p=>{const h=((p.signNumber-L.signNumber+12)%12)+1;
 console.log(p.name.padEnd(8),p.signName.padEnd(12),p.degreeInSign.toFixed(2).padStart(6),'H'+h,p.nakshatra,p.retrograde?'R':'',p.dignity||'');});
let nak=m.nakshatra; if(nak==='Mula')nak='Moola';
const d=A.calculateVimshottariDasha(new Date('1995-12-02T15:30:00+05:45'),nak,(m.longitude%13.3333333),3);
const T=new Date('2026-08-16');
const md=d.mahaDashas.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
const ad=md.subPeriods.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
const pd=(ad.subPeriods||[]).find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
console.log('\nMD',md.planet,(''+md.startDate).slice(0,10),(''+md.endDate).slice(0,10));
console.log('AD',ad.planet,(''+ad.startDate).slice(0,10),(''+ad.endDate).slice(0,10));
console.log('PD',pd&&pd.planet,pd&&(''+pd.startDate).slice(0,10),pd&&(''+pd.endDate).slice(0,10));
console.log('\n-- ADs in current MD --');
md.subPeriods.forEach(p=>console.log('  ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('\n-- MD timeline --');
d.mahaDashas.forEach(p=>console.log('  ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('\n-- SWEEP +-15min --');
[-15,-10,-5,0,5,10,15].forEach(o=>{const t=new Date(Date.UTC(1995,11,2,15,30)+o*60000);
 const rr=A.calculateBirthChart({...B,time:String(t.getUTCHours()).padStart(2,'0')+':'+String(t.getUTCMinutes()).padStart(2,'0')});
 console.log('  ',(o+'min').padStart(6),'D1',rr.lagna.signName,rr.lagna.degreeInSign.toFixed(2));});
console.log('\n-- TRANSITS (Sade Sati check, Moon sign above) --');
['2023-01-17','2025-03-29','2026-08-16','2027-07-01','2028-01-01','2029-01-01','2030-01-01'].forEach(ds=>{
 const t=A.calculateBirthChart({date:ds,time:'12:00',latitude:26.6,longitude:87.9,timezone:'Asia/Kathmandu'});
 const tp=Array.isArray(t.planets)?t.planets:Object.values(t.planets);
 const sa=tp.find(x=>x.name==='Saturn'),ju=tp.find(x=>x.name==='Jupiter'),ra=tp.find(x=>x.name==='Rahu');
 console.log('  ',ds,'Sa:',sa.signName,sa.degreeInSign.toFixed(1),' Ju:',ju.signName,ju.degreeInSign.toFixed(1),' Ra:',ra.signName,ra.degreeInSign.toFixed(1));});
