const A=require('./index.js');
const B={date:'1993-02-17',time:'04:00',latitude:27.2167,longitude:86.8000,timezone:'Asia/Kathmandu'};
const r=A.calculateBirthChart(B);
const pl=Array.isArray(r.planets)?r.planets:Object.values(r.planets);
const L=r.lagna,m=pl.find(p=>p.name==='Moon');
console.log('LAGNA',L.signName,L.degreeInSign.toFixed(2));
pl.forEach(p=>{const h=((p.signNumber-L.signNumber+12)%12)+1;
 console.log(p.name.padEnd(8),p.signName.padEnd(12),p.degreeInSign.toFixed(2).padStart(6),'H'+h,p.nakshatra,p.retrograde?'R':'',p.dignity||'');});
let nak=m.nakshatra; if(nak==='Mula')nak='Moola';
const d=A.calculateVimshottariDasha(new Date('1993-02-17T04:00:00+05:45'),nak,(m.longitude%13.3333333),3);
const T=new Date('2026-08-16');
const md=d.mahaDashas.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
const ad=md.subPeriods.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
console.log('\nMD',md.planet,(''+md.startDate).slice(0,10),(''+md.endDate).slice(0,10));
console.log('AD',ad.planet,(''+ad.startDate).slice(0,10),(''+ad.endDate).slice(0,10));
console.log('\n-- ADs in current MD --');
md.subPeriods.forEach(p=>console.log('  ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('\n-- MD timeline --');
d.mahaDashas.forEach(p=>console.log('  ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('\n-- YOGAS --');
const y=A.detectYogas(pl,r.houses,L.signNumber);
(Array.isArray(y)?y:Object.values(y)).forEach(g=>console.log('  *',g.name,'|',(g.description||'').slice(0,100)));
console.log('\n-- MANGLIK --'); console.log(JSON.stringify(A.analyzeManglik(pl,L.signNumber)).slice(0,400));
console.log('\n-- SWEEP +-15min (D1 / D9 lagna) --');
[-15,-10,-5,0,5,10,15].forEach(o=>{const t=new Date(Date.UTC(1993,1,17,4,0)+o*60000);
 const rr=A.calculateBirthChart({...B,time:String(t.getUTCHours()).padStart(2,'0')+':'+String(t.getUTCMinutes()).padStart(2,'0')});
 const rp=Array.isArray(rr.planets)?rr.planets:Object.values(rr.planets);
 const d9=A.calculateDivisionalChart(9,rp,rr.lagna.signNumber,rr.lagna.degreeInSign);
 console.log('  ',(o+'min').padStart(6),'D1',rr.lagna.signName,rr.lagna.degreeInSign.toFixed(2),'| D9',d9.lagna&&d9.lagna.name);});
