const fs=require('fs');
const P='/Users/saurabh/Desktop/Jyotish /pandit_state.json';
const READING=`Umesh ji, I have both children's charts now. You sent their times but not their birth places, so I have read both taking Birgunj since that is your city. I checked whether it matters and it does not, the ascendant comes out the same whether they were born in Birgunj or Kathmandu, so these readings stand. Tell me only if one of them was born outside Nepal.

Upashna's chart is the stronger of the two. Her ascendant is Libra and Venus, its lord, sits in Libra in the ascendant itself in its own sign, which gives good judgement, taste and a personality people warm to, and her Moon is exalted so her temperament is sound. On study, you may already be seeing what her chart shows. Rahu sits in her fifth house of education in its own sign, which makes her bright but not conventional, her interest jumps about and she does far better in practical, technical or computer related subjects than in pure memorising. Her Mercury is combust, so her marks tend to understate what she actually knows, do not judge her by results alone. Between April 2027 and April 2028 she runs a Ketu period and a break or a change of direction in her studies is likely in it, so if she asks to change her line, let her, rather than forcing her to continue. From April 2028 she begins three years of Venus, her own ascendant lord, and that is when it all settles and she does well. On marriage, her seventh lord Mars is retrograde in the ninth house, so the match is likely to come from another city and the matter will need a second look before it is fixed. Do not hurry it before 2028, the likely stretch is 2030 to 2035. And she is not Manglik from her ascendant, so let nobody frighten you on that point.

Yesh has a quieter chart but a well protected one. Cancer ascendant with the Moon in its own sign right in the ascendant, so he is sensitive, attached to home and straight in his dealings. Venus sits in its own sign in his fourth house, strong for comfort, for his mother and for education. Best of all, Jupiter sits in its own sign in his ninth house of fortune and higher learning, which means he will do noticeably better in college than he does in school, so do not lose patience with him in these years. His Mercury is retrograde and combust in the fifth house, so his studies are slow to show, he understands deeply but needs repetition, and the results lift properly from December 2027 when his Venus period starts and runs for three years. Sun, Mars and Rahu together in his sixth house make him a competitor, so technical lines and competitive examinations suit him better than a soft path. Marriage for him is settled but late, his seventh lord is Saturn which asks for maturity, so expect it in his late twenties or after thirty, and to a steady rather than a showy partner.

Now your own work, since you said the last answer was not clear enough. You are in Mercury mahadasha until 7 July 2038. That is the plain answer to how long you can run this business, twelve more strong working years, and the business stays yours through all of them. From 7 July 2038 your Ketu mahadasha begins, and Ketu sits in your tenth house of work, which pulls a man's interest out of his own business. That is the point to hand over, not to be pushed out of. Yesh will be twenty seven then and Upashna thirty, so plan the handover for those years instead of resisting it. What follows is the good part. From July 2045 your Venus mahadasha begins and runs twenty years, with Venus strong in your own ascendant, so old age is materially the best stretch of your whole chart, comfortable and respected. Not many people can be told that honestly.

On the house, the window I gave you was October 2027 to August 2028. You will be forty seven turning forty eight. That is the age you buy it.

On a manufacturing business, your fourth house holds Mars, Saturn, Jupiter and Rahu together in Leo, which is fire, iron, labour and machinery all sitting in one place. So a plant that works with heat or metal suits you, fabrication, machinery parts, plastics or packaging, or the processing of a raw material. Your real edge is this, you already know clearing and forwarding, so the right unit for you is one whose raw material you import yourself. That is where your two strengths join instead of competing. Start it in 2030 during your Mars period, and keep away from starting between January 2031 and July 2033, which is your Rahu period and the wrong time to sink capital into a new plant. About Punam I cannot say anything yet, you have not given me her date, time or place of birth. Send those and I will tell you whether the business should stand in her name or in yours, which for a manufacturing licence is worth knowing before you register it.`;
const s=JSON.parse(fs.readFileSync(P,'utf8'));
const x=s.sessions.find(v=>v.id==='s547');
x.person.children=[{name:'Upashna',dob:'2007-12-23',time:'03:50',place:'Birgunj (assumed)'},{name:'Yesh',dob:'2010-12-23',time:'20:30',place:'Birgunj (assumed)'}];
const nid=Math.max(0,...(x.messages||[]).map(v=>v.id||0))+1;
x.messages.push({id:nid,role:'pandit',text:READING});
x.pending=false;
s.pandit.activity='s547 Umesh — 2 chhoraachhori ko chart, kaam 2038 samma, ghar umer 47-48, manufacturing 2030';
fs.writeFileSync(P,JSON.stringify(s,null,1));
console.log('OK msg',nid);
