const A=require('./index.js');
// Thapathali Kathmandu 27.6928N 85.3169E; 9 Sep 1995 23:33 NPT => UTC 17:48
const birth={date:'1995-09-09',time:'23:33',latitude:27.6928,longitude:85.3169,timezone:'Asia/Kathmandu'};
const res=A.calculateBirthChart(birth);
const plist=Array.isArray(res.planets)?res.planets:Object.values(res.planets);
const m=plist.find(p=>p.name==='Moon');
console.log('LAGNA',res.lagna.signName,res.lagna.signNumber,res.lagna.nakshatra,'deg',res.lagna.degreeInSign,'| MOON',m.signName,m.nakshatra);
(res.houses||[]).forEach(h=>console.log('H'+(h.houseNumber||h.number),h.signName||h.sign,(h.planets||[]).map(x=>x.name||x).join(',')));
plist.forEach(p=>console.log('P',p.name,p.signName,'deg='+p.degreeInSign,'nak='+p.nakshatra,'pada='+p.nakshatraPada,'dig='+p.dignity,'retro='+p.retrograde,'combust='+p.isCombust));
const L=res.lagna;
const d9=A.calculateDivisionalChart(9,plist,L.signNumber,L.degreeInSign);
const lag=d9.lagnaSign.number;
console.log('D9 LAGNA',d9.lagnaSign.name);
d9.planets.forEach(p=>console.log('D9',p.planet,p.vargaSignName,'house='+(((p.vargaSignNumber-lag+12)%12)+1)));
const d=A.calculateVimshottariDasha(new Date('1995-09-09T17:48:00Z'),m.nakshatra,(m.longitude%13.3333333),3);
const TODAY=new Date('2026-07-19');
const md=d.mahaDashas.find(p=>new Date(p.startDate)<=TODAY&&new Date(p.endDate)>TODAY);
console.log('MD',md.planet,(''+md.startDate).slice(0,10),'→',(''+md.endDate).slice(0,10));
md.subPeriods.forEach(p=>{if(new Date(p.endDate)>new Date('2025-06-01')&&new Date(p.startDate)<new Date('2032-01-01'))console.log(' AD',p.planet,(''+p.startDate).slice(0,10),'→',(''+p.endDate).slice(0,10));});
const ad=md.subPeriods.find(p=>new Date(p.startDate)<=TODAY&&new Date(p.endDate)>TODAY);
console.log('CUR AD',ad.planet);
(ad.subPeriods||[]).forEach(p=>console.log('   PD',p.planet,(''+p.startDate).slice(0,10),'→',(''+p.endDate).slice(0,10)));
