const A=require('./index.js');
const B={date:'2000-05-12',time:'10:00',latitude:27.5833,longitude:85.5167,timezone:'Asia/Kathmandu'};
const r=A.calculateBirthChart(B);
const pl=Array.isArray(r.planets)?r.planets:Object.values(r.planets);
const L=r.lagna,m=pl.find(p=>p.name==='Moon');
const SN=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
console.log('LAGNA',L.signName,L.degreeInSign.toFixed(2));
pl.forEach(p=>{const h=((p.signNumber-L.signNumber+12)%12)+1;
 console.log(p.name,p.signName,p.degreeInSign.toFixed(2),'H'+h,p.nakshatra,p.retrograde?'R':'',p.dignity||'');});
let nak=m.nakshatra; if(nak==='Mula')nak='Moola';
const d=A.calculateVimshottariDasha(new Date('2000-05-12T10:00:00+05:45'),nak,(m.longitude%13.3333333),3);
const T=new Date('2026-08-16');
const md=d.mahaDashas.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
const ad=md.subPeriods.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
const pd=ad.subPeriods&&ad.subPeriods.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
console.log('\nMD',md.planet,(''+md.startDate).slice(0,10),(''+md.endDate).slice(0,10));
console.log('AD',ad.planet,(''+ad.startDate).slice(0,10),(''+ad.endDate).slice(0,10),'| PD',pd&&pd.planet,pd&&(''+pd.startDate).slice(0,10),pd&&(''+pd.endDate).slice(0,10));
console.log('\n-- ADs in current MD --');
md.subPeriods.forEach(p=>console.log(' ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('\n-- PDs inside current AD --');
(ad.subPeriods||[]).forEach(p=>console.log('   ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('\n-- MD timeline --');
d.mahaDashas.forEach(p=>console.log(' ',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
console.log('\n-- YOGAS --');
A.detectYogas(r.planets,r.houses,L.signNumber).forEach(g=>console.log(' *',g.name));
console.log('\n-- LAGNA SWEEP +-10min --');
[-10,-5,0,5,10].forEach(o=>{const t=new Date(Date.UTC(2000,4,12,10,0)+o*60000);
 const rr=A.calculateBirthChart({...B,time:String(t.getUTCHours()).padStart(2,'0')+':'+String(t.getUTCMinutes()).padStart(2,'0')});
 const d9=A.calculateDivisionalChart(9,Array.isArray(rr.planets)?rr.planets:Object.values(rr.planets),rr.lagna.signNumber,rr.lagna.degreeInSign);
 console.log('  ',o+'min D1',rr.lagna.signName,rr.lagna.degreeInSign.toFixed(2),'| D9',d9.lagna&&d9.lagna.name);});
