const A=require('./index.js');
const B={date:'2001-03-23',time:'05:10',latitude:28.0000,longitude:84.6333,timezone:'Asia/Kathmandu'};
const ISO='2001-03-23T05:10:00+05:45';
[-10,0,10].forEach(off=>{
 const [h,mi]=B.time.split(':').map(Number);let tot=h*60+mi+off;
 const tt=String(Math.floor(tot/60)).padStart(2,'0')+':'+String(tot%60).padStart(2,'0');
 const r=A.calculateBirthChart({...B,time:tt});
 const pl=Array.isArray(r.planets)?r.planets:Object.values(r.planets);
 const mo=pl.find(p=>p.name==='Moon');
 const d9=A.calculateDivisionalChart(9,pl.map(p=>({name:p.name,signNumber:p.signNumber,degreeInSign:p.degreeInSign})),r.lagna.signNumber,r.lagna.degreeInSign);
 console.log('SENS',off+'min',tt,'lagna',r.lagna.signName,r.lagna.degreeInSign.toFixed(2),'| D9 lagna',d9.lagnaSign.name,'| Moon',mo.signName,mo.nakshatra,'pada'+(mo.nakshatraPada||mo.pada));
});
const r=A.calculateBirthChart(B);
const pl=Array.isArray(r.planets)?r.planets:Object.values(r.planets);
const L=r.lagna,m=pl.find(p=>p.name==='Moon');
console.log('\n===== LAGNA '+L.signName+'('+L.signNumber+') '+L.degreeInSign.toFixed(2)+' '+L.nakshatra);
pl.forEach(p=>console.log('  ',p.name,p.signName,p.signNumber,p.degreeInSign.toFixed(2),'H'+(((p.signNumber-L.signNumber+12)%12)+1),p.nakshatra,'pada'+(p.nakshatraPada||p.pada||''),p.dignity,(p.retrograde?'R':''),(p.isCombust?'CMB':'')));
const hFrom=(a,b)=>((a-b+12)%12)+1;
const ma=pl.find(p=>p.name==='Mars'),ve=pl.find(p=>p.name==='Venus');
console.log('   MANGLIK fromLagna H'+hFrom(ma.signNumber,L.signNumber),'fromMoon H'+hFrom(ma.signNumber,m.signNumber),'fromVenus H'+hFrom(ma.signNumber,ve.signNumber));
const d9=A.calculateDivisionalChart(9,pl.map(p=>({name:p.name,signNumber:p.signNumber,degreeInSign:p.degreeInSign})),L.signNumber,L.degreeInSign);
console.log('   D9 lagna',d9.lagnaSign.name,d9.lagnaSign.number);
d9.planets.forEach(p=>console.log('      D9',p.planet,p.vargaSignName,'H'+(((p.vargaSignNumber-d9.lagnaSign.number+12)%12)+1)));
let nak=m.nakshatra; if(nak==='Mula')nak='Moola';
const d=A.calculateVimshottariDasha(new Date(ISO),nak,(m.longitude%13.3333333),3);
const T=new Date('2026-08-05');
const md=d.mahaDashas.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
console.log('\n MD '+md.planet+' '+(''+md.startDate).slice(0,10)+' -> '+(''+md.endDate).slice(0,10));
md.subPeriods.forEach(p=>console.log('   AD',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
const ad=md.subPeriods.find(p=>new Date(p.startDate)<=T&&new Date(p.endDate)>T);
console.log('   CUR AD',ad.planet);
(ad.subPeriods||[]).forEach(p=>console.log('      PD',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));
const ni=d.mahaDashas.indexOf(md)+1;
[ni,ni+1].forEach(i=>{const n=d.mahaDashas[i];if(!n)return;
 console.log('   MD',n.planet,(''+n.startDate).slice(0,10),'->',(''+n.endDate).slice(0,10));
 n.subPeriods.slice(0,6).forEach(p=>console.log('      AD',p.planet,(''+p.startDate).slice(0,10),'->',(''+p.endDate).slice(0,10)));});
// house cusps / signs for kundli build
console.log('\nHOUSES');
for(let i=0;i<12;i++){const sn=((L.signNumber-1+i)%12)+1;
 const occ=pl.filter(p=>p.signNumber===sn).map(p=>p.name);
 console.log('  H'+(i+1),sn,occ.join(','));}
