const fs=require('fs');
const P='/Users/saurabh/Desktop/Jyotish /pandit_state.json';
// s91 Shri, paid follow-up on family dynamics. Chart already stored on the session.
// Family charts read AS GIVEN (he has no birth times for them), so no dasha dates invented for them.
const READING=`Before anything else, one structural thing that reorganises your whole question. Your fourth house holds Rahu debilitated, alongside Venus and Mercury. The fourth is the house of the mother and it is also the house of the home itself, the physical place you live and who is allowed inside it. So the two things you wrote to me as separate complaints, that your mother is the poorest relationship of them all, and that you do not want any of them or any guest at all in your place, are not two problems. They are one placement seen from two sides. Rahu there makes the home feel like something that can be invaded, and it puts the same static into the mother bond. Your caution about visitors is not you being difficult, it is your fourth house, and while this period runs I would follow that instinct rather than argue with it.

Which brings me to the date you actually want. You have been in Rahu mahadasha since September 2010, and that Rahu is the debilitated one sitting in the fourth. Eighteen years of your life have run under the planet that occupies your mother and home house, which is precisely why this whole territory has been the loud thing for so long. It ends on 28 September 2028. Jupiter takes over then for sixteen years, and your Jupiter sits in the second house, which is the house of family as a body, the kutumb. So the family theme does not disappear from your life, it changes hands. It moves from being run by a debilitated Rahu to being run by Jupiter, and that is the difference between agitation and steadiness. I told you before that this Jupiter is in Virgo in an enemy sign and is not strong on its own account, and that is still true. It does not need to be strong. It needs to be Jupiter sitting in the family house instead of Rahu sitting in the mother house, and from September 2028 that is what you get.

On whether their dasha changes will help, I have to separate them, because the answer is not the same for each. The sibling moving from Saturn into Mercury is the one I would not hold hope for. In the chart you gave me Mercury sits in their ascendant conjoined Rahu, and Mercury also owns their sixth house of conflict. A mahadasha of a planet that Rahu is sitting on, in the ascendant, tends to amplify self image and the managing of appearances rather than soften them, and a sixth lord period does not usually make a person easier to deal with. What you described, the inability to face you one to one and the reliance on gathering others to do it, is coalition behaviour, and Rahu on Mercury in the first house is exactly that instinct. Plan for continuity there, not improvement.

The Bharani sibling is different and you already know it. Jupiter with the Moon in the twelfth is a genuinely devotional placement, and the twelfth is where a person's private inner life lives, which is why the mandir and the jyotish talk are where the two of you actually meet. That is not a small overlap, it is the real channel between you, and it will hold. Keep feeding that one specifically rather than trying to make the general family relationship better as a whole.

About your mother, I am going to be straight with you because I think you have been waiting a long time for someone to be. Saturn retrograde sits with Ketu in her ascendant, and her Moon is in the twelfth in Moola. Saturn with Ketu on the ascendant is rigidity together with detachment, and a Moon in the twelfth in Moola is one of the more isolated emotional placements a chart can carry, a mind rooted in upheaval and turned away from the world. Her own fourth house carries Rahu, the same disturbance in the mother line that you carry in yours, one generation up. What that adds to is not a woman who is withholding warmth from you deliberately. It is a chart in which that channel was never open. You are not failing to reach her. There is not a version of you that reaches her. I would let go of the expectation rather than keep testing it, and let whatever civil contact exists be the whole of it.

Your father reads quite differently and it confirms what you said about him. His Jupiter is in its own sign in the third house, and the third is speech and teaching and the passing on of things. That is the religious instruction you received all through your life, and it is the single most useful placement across all four of those charts as far as you are concerned. Your own ninth house is empty and your Sun, who signifies the father, is debilitated in your third, which is the absence you felt. But your ninth lord Mars sits in your eleventh, and the ninth is dharma, so with him the relationship works through shared belief and at a distance rather than through daily closeness. That is not a consolation prize, it is the actual shape of that bond, and it is why it improved with age. Use it as it is.

One more thing you did not ask about but which fell out of your own chart while I was looking. You have Mars in the eleventh house, and the eleventh is friend circles and networks. You described a sibling who isolated you from your friends. That is an eleventh house injury quite precisely, and Mars is the planet sitting there. It happened to you in the exact house where it would land hardest, which is worth knowing, because it explains why that particular cruelty went as deep as it did rather than sliding off.

Finally the thing underneath all of it. Saturn is in his own sign in your sixth house with the Moon, and the sixth is service, debt and obligation. Giving substantially and receiving little back is not bad luck repeating itself, it is that pair, and money flowing out to family without return is about as literal a sixth house expression as exists. So when you say that at some point you have to be honest and respect your own life and stop accommodating people who are opposed to you, understand that you are not abandoning a duty. With Saturn in the sixth, holding a boundary is the correct handling of the placement, not a failure of it. And Jupiter's aspect from your second house falls straight onto that Moon and Saturn pair, which is the release of exactly this pattern, and it becomes the ruling influence of your life from 28 September 2028. You are two years out from the period that undoes the thing you are tired of.`;
const s=JSON.parse(fs.readFileSync(P,'utf8'));
const x=s.sessions.find(v=>v.id==='s91');
const nid=Math.max(0,...(x.messages||[]).map(v=>v.id||0))+1;
x.messages.push({id:nid,role:'pandit',text:READING});
x.pending=false;
x.awaiting=false;
s.pandit.activity='s91 Shri — parivar, Rahu neech 4th (mata+ghar ek hi bhav), Rahu MD ends 28 Sep 2028, Guru MD 2nd bhav ma';
fs.writeFileSync(P,JSON.stringify(s,null,1));
console.log('OK msg',nid,'| messages now',x.messages.length,'| pending',x.pending);
